version: '3'

services:
  app:
    image: omar421/depi-go:latest
    build: .
    ports:
      - "8084:8084"
    depends_on:
      - db
    environment:
      SERVER_PORT: 8084
      MONGO_URI: mongodb://db:27017

  db:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
