apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-deploy
  namespace: go-depi
  labels:
    app: go-app
spec:
  selector:
    matchLabels:
      app: go-app
  replicas: 2
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
        - name: go-app
          image: omar421/depi-go:latest
          ports:
            - containerPort: 8084
          env:
            - name: MONGODB_URI
              value: "mongodb://mongo-app-service:27017"
            - name: SERVER_PORT
              value: "8084"
        - name: mongo-app
          image: mongo:latest
          ports:
            - containerPort: 27017
